name: Keep Alive

on:
  schedule:
    - cron: '0 6 */6 * *'

jobs:
  visit-website:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Puppeteer
      run: npm install puppeteer

    - name: Run script
      run: node script.js