name: Keep Alive

on:
  schedule:
    - cron: '0 6 */6 * *'
  workflow_dispatch:

jobs:
  visit-website:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Create .env
      run: | 
        echo USERNAME=${{ secrets.USERNAME }} >> .env
        echo PASSWORD=${{ secrets.PASSWORD }} >> .env

    - name: Run script
      run: node script.js